# Generated by Django 4.1.7 on 2023-03-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutkeriapp', '0002_alter_kyc_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_bp', models.IntegerField()),
                ('lower_bp', models.IntegerField()),
                ('blood_sugar', models.FloatField()),
                ('body_temp', models.FloatField()),
                ('heart_rate', models.IntegerField()),
            ],
        ),
    ]
