# Generated by Django 4.1.7 on 2023-03-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutkeriapp', '0003_health_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_parameter',
            name='heart_rate',
        ),
        migrations.AddField(
            model_name='kyc',
            name='Husband_name',
            field=models.CharField(blank='True', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='kyc',
            name='First_name',
            field=models.CharField(max_length=100),
        ),
    ]
