# Generated by Django 4.1.7 on 2023-03-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutkeriapp', '0005_rename_dob_kyc_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health_parameter',
            old_name='blood_sugar',
            new_name='Blood_Sugar',
        ),
        migrations.RenameField(
            model_name='health_parameter',
            old_name='body_temp',
            new_name='Body_Temperature',
        ),
        migrations.RenameField(
            model_name='health_parameter',
            old_name='lower_bp',
            new_name='Diastolic_BP',
        ),
        migrations.RenameField(
            model_name='health_parameter',
            old_name='upper_bp',
            new_name='Systolic_BP',
        ),
        migrations.AlterField(
            model_name='kyc',
            name='Address',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
    ]
